language: rust

git:
  depth: false

dist: trusty
sudo: required

cache:
  cargo: true
  timeout: 240
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/target/tmp

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

env:
  global:
    - RUST_BACKTRACE="1"
    - RUST_FLAGS="-C debug-assertions"

matrix:
  include:
    - os: linux
      env: TEST_SUITE=config-libwallet-apiwallet
    - os: linux
      env: TEST_SUITE=refwallet-.
    - os: osx
      env: TEST_SUITE=release

script:
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[0]};
    echo "start testing on folder $DIR...";
    if [[ -n "$DIR" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]];  then cd $DIR && cargo test --release && cd - > /dev/null; fi;
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[1]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[2]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;

before_deploy:
  - if [[ "$TEST_SUITE" == "pool-p2p-src" ]]; then
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]]  && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: OJRcSVApoEJbWd0ruvAZqxROql0pdGHrOvzXW8HekHF+pqxhjNAcrOk41413VjU+UMVAKjKAfCilxIg4MGGrMssM5h9PyNBKN1ADue1gnHECZUTaapCS/5o1caRJETpY5O7SMr3XSosQ13158M3nbzrp3Q9oZ9Ff1IPgVOk4n1tSyIh6EKc5pt7HPdtTZC6EaRQMjgGzLiN453pemML8cN1KE7lnNA8ie0sG9f8PLvXvBC2pT6lwE34pVINwIGYqJeKzwAs/FTYG2mDwwOGXX568G5irRCvqV8N+0qsj9CAjj4fHqTBcyP7K7AEGNglGr1m6N6jJHgfTuk9ifs1khuj9KVR5syLoZ4IkkFraLQUYrKa4/efgVH6gSAGG9wLBt2vosPt9QoXh6XyDSJEBkobTA5xnlqACbWHE8+maSAZO6YkOSnEUttYPffjwYSpUNDVONtxf2Grhs1eCHHnoiNI18D0mOFHAi32LJFSLDMZriXVTRFovg0pvEiRDJf71IJM4cQ0SwV2b6InGmH6fyrn3mv6TthPELiQtacJT/ucWqT5t/6vjhFsBOBXmKhmV87lpMS3pyCoriB8/JvcJnGVPOnxC6+MnD1BzfiR3CL0vKgK0URTB2+Z1IxhjyI8quuZCIgiE3A0Da9b0YH/9g7h1ONnxDIaOQdf6d7TcWSQ=
  file_glob: true
  file: target/release/grin-wallet-*.tgz*
  skip_cleanup: true
  on:
    repo: mimblewimble/grin-wallet
    tags: true
