language: rust

git:
  depth: false

dist: trusty
sudo: required

cache:
  cargo: true
  timeout: 240
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/target/tmp

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

env:
  global:
    - RUST_BACKTRACE="1"
    - RUST_FLAGS="-C debug-assertions"

matrix:
  include:
#    - os: linux
#      env: TEST_SUITE=integration
#    - os: linux
#      env: TEST_SUITE=config-libwallet-apiwallet
#    - os: linux
#      env: TEST_SUITE=refwallet-.
#    - os: osx
#      env: TEST_SUITE=release
    - os: windows 
      env: TEST_SUITE=release

script:
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[0]};
    echo "start testing on folder $DIR...";
    if [[ -n "$DIR" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]];  then cd $DIR && cargo test --release && cd - > /dev/null; fi;
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[1]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;
  - IFS='-' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[2]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;

before_deploy:
  - if [[ "$TEST_SUITE" == "refwallet-." ]]; then
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]]  && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]]  && [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cargo clean && cargo build --release && ./.auto-release.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: PCNX/DheeQWCGT1XLTbE7GKSd5y+NVZ6KSn+E6USzOX4Rc50Ihpr0jvf5NqQRUnglLG/ftl9bBsaD8URnOBdd4mbo5hNm1raV57PkFQX6rkXQ8oYXgTajUxNLoDWcUgsQDqUOOAJeakFXy2Olb66uTmnfvGtkwcAzGk2ZXvI8rUGCN+7v+dyvbR9N16etfn8aN/Rm8TMQyQkbMU9xENOu6CqBknCq+jhi4FOhB6k4Kcnwhu/Z+E278zgeIHQWfGStZKk+wk7DQU3qGGoYhTGQ2E1Ew8r1jnwdgAB0nvYuXWiSu8hXO0hFJWofDro/Wj7lFXGugRTJ7jANrTsZhopR9G2lyYQIGAJJ0+KRozRDDuxQxCNlHoG95NWleDXR9/FinhW1FqZai1hsW12vQWO1+SaDqzmBF9jCIYnx7RWLfoLqzpJUsPk0Fzl5gJexQKWvE4udfi657426qV/tgWXFjqpFrekVFyun1ie5vSTx33MNnGfvmhyqsXEsorpWWiouSkIlBkckyF97CjOG76XQJ11M5ICqH/vn7z90KUR/S/N60yYFEcueoMMzz617Ag+m4Irgl0ajaEeu4senUMIOfwq/S5mlRAY3FQA9mh4MbgO3g1EtuxDvCA4RiFnLakI1U0/peOYAdjQ+S7v3B86wUBMYTbpRgeLISa1CsaSm3Y=
  file_glob: true
  file: target/release/grin-wallet-*.*
  skip_cleanup: true
  on:
    repo: mimblewimble/grin-wallet
    tags: true
